import mongoose from "mongoose";

// Single-use signed token for email unsubscribe confirmation.
// Generated by the reminder job before each send; included as a link in the email.
// Consumed via POST /api/unsubscribe/consume — marks usedAt, writes suppression.
const EmailUnsubscribeTokenSchema = new mongoose.Schema(
    {
        emailNormalized: {
            type: String,
            required: true,
            trim: true,
            lowercase: true,
            index: true,
        },
        tokenHash: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },
        expiresAt: {
            type: Date,
            required: true,
            index: true,
        },
        usedAt: {
            type: Date,
            default: null,
            index: true,
        },
    },
    { timestamps: true },
);

export default mongoose.model(
    "EmailUnsubscribeToken",
    EmailUnsubscribeTokenSchema,
);
