export const SOCIAL_STYLES = Object.freeze([
    "pills",
    "pillsWide",
    "icons",
    "iconsDense",
]);

// Rollback: use inline PNG placeholder instead of public/ paths
const PREVIEW_PLACEHOLDER_PNG =
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO3Z2qAAAAAASUVORK5CYII=";

export const TEMPLATES = [
    {
        id: "roismanA11yLight",
        label: "Roisman A11y Light",
        name: "מפרץ",
        skinKey: "roismanA11y",
        group: "light",
        previewImage:
            "/templates/previews/preview-covers/roismana11ylight.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },
    {
        id: "lakmi",
        label: "Lakmi",
        name: "ורד-זהב",
        skinKey: "lakmi",
        group: "light",
        previewImage: "/templates/previews/preview-covers/lakmi.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },
    // Variant A: token-only skin; shared CardLayout skeleton.
    {
        id: "beauty",
        skinKey: "beauty",
        group: "light",
        name: "שקד",
        backgroundMode: "photo",
        previewImage: "/templates/previews/preview-covers/beauty.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            gallery: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "center",
            socialStyle: "icons",
            backgroundOverlay: 40,
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "תשובות קצרות וברורות שיעזרו לכם להחליט במהירות.",
                items: [
                    {
                        q: "מה כלול בשירות?",
                        a: "שיחת היכרות, התאמת פתרון לצורך, וליווי קצר כדי לוודא שהכול עובד כמו שצריך.",
                    },
                    {
                        q: "אפשר לקבל הצעת מחיר?",
                        a: "כן. כתבו לי בהודעה קצרה, ואחזור אליכם עם הצעה שמתאימה בדיוק למה שאתם צריכים.",
                    },
                    {
                        q: "כמה מהר אפשר להתחיל?",
                        a: "בדרך כלל אפשר להתחיל כבר בימים הקרובים, בהתאם לזמינות ולדחיפות.",
                    },
                ],
            },
        },
    },
    {
        id: "galit",
        label: "Galit",
        name: "אבן-שמיים",
        skinKey: "galit",
        group: "light",
        previewImage: "/templates/previews/preview-covers/galit.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "customV1",
        skinKey: "self",
        name: "עיצוב עצמי",
        selfThemeV1: true,
        backgroundMode: "photo",
        previewImage: PREVIEW_PLACEHOLDER_PNG,
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            gallery: true,
            cta: true,
            socials: true,
            contact: true,
        },
        // Palette-only customization (renderer applies palette classes, no inline styles)
        designDefaults: {
            templateId: "customV1",
            backgroundOverlay: 40,
        },
        seededFields: [
            "name",
            "headline",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "Custom Card",
            headline: "Pick a palette",
            about: "Class-based palettes only (safe, no inline styles).",
            faq: {
                title: "שאלות ותשובות",
                lead: "מענה קצר על הדברים החשובים לפני שמתחילים.",
                items: [
                    {
                        q: "אפשר לערוך אחר כך?",
                        a: "כן. אפשר לעדכן את השאלות והתשובות בכל זמן דרך העורך.",
                    },
                    {
                        q: "זה מתאים גם ל-RTL?",
                        a: "כן. הסקשן בנוי RTL-first ומשתמש ב-flex ובערכי טוקנים.",
                    },
                    {
                        q: "האם זה משפיע על SEO?",
                        a: "כן. נוצרת גם סכמת JSON-LD מסוג FAQPage בצורה מסונכרנת מהנתונים.",
                    },
                ],
            },
            cta: { label: "Contact", value: "https://wa.me/972501112233" },
            contact: {
                phone: "+972-50-111-2233",
                email: "hello@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "irisLayla",
        label: "Iris Layla",
        name: "איריס-לילה",
        skinKey: "irisLayla",
        group: "light",
        previewImage: "/templates/previews/preview-covers/iris-layla.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "shkiyaLaguna",
        label: "Shkiya Laguna",
        name: "שקיעה-לגונה",
        skinKey: "shkiyaLaguna",
        group: "light",
        previewImage: "/templates/previews/preview-covers/shkiya-laguna.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "zahavLaguna",
        label: "Zahav Laguna",
        name: "זהב-לגונה",
        skinKey: "zahavLaguna",
        group: "light",
        previewImage: "/templates/previews/preview-covers/zahav-laguna.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "rubyEsh",
        label: "Ruby Esh",
        name: "רובי-אש",
        skinKey: "rubyEsh",
        group: "light",
        previewImage: "/templates/previews/preview-covers/ruby-esh.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "shachorGraphit",
        label: "Shachor Graphit",
        name: "שחור-גרפיט",
        skinKey: "shachorGraphit",
        group: "light",
        previewImage: "/templates/previews/preview-covers/shachor-graphit.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "pardesChai",
        label: "Pardes Chai",
        name: "פרדס-חי",
        skinKey: "pardesChai",
        group: "light",
        previewImage: "/templates/previews/preview-covers/pardes-chai.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "bronzeSachlav",
        label: "Bronze Sachlav",
        name: "ברונזה-סחלב",
        skinKey: "bronzeSachlav",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/bronze-sachlav.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: {
                label: "שיחה מהירה בוואטסאפ",
                value: "https://wa.me/972501234567",
            },
            contact: {
                phone: "+972-50-123-4567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                {
                    platform: "linkedin",
                    url: "https://www.linkedin.com/in/example",
                },
                {
                    platform: "instagram",
                    url: "https://www.instagram.com/example",
                },
            ],
        },
    },

    {
        id: "tehomTurkiz",
        label: "Tehom Turkiz",
        name: "תהום-טורקיז",
        skinKey: "tehomTurkiz",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/tehom-turkiz.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "inbarAdama",
        label: "Inbar Adama",
        name: "ענבר-אדמה",
        skinKey: "inbarAdama",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/inbar-adama.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "lavaLaguna",
        label: "Lava Laguna",
        name: "לבה-לגונה",
        skinKey: "lavaLaguna",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/lava-laguna.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "zahavTehom",
        label: "Zahav Tehom",
        name: "זהב-תהום",
        skinKey: "zahavTehom",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/zahav-tehom.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "evenNil",
        label: "Even Nil",
        name: "אבן-נילוס",
        skinKey: "evenNil",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/even-nil.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "irisChatzot",
        label: "Iris Chatzot",
        name: "איריס-חצות",
        skinKey: "irisChatzot",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/iris-chatzot.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "gacheletArgaman",
        label: "Gachelet Argaman",
        name: "גחלת-ארגמן",
        skinKey: "gacheletArgaman",
        group: "dark",
        previewImage:
            "/templates/previews/preview-covers/gachelet-argaman.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחושת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "bronzeChol",
        label: "Bronze Chol",
        name: "ברונזה-חול",
        skinKey: "bronzeChol",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/bronze-chol.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    {
        id: "hadarGachelet",
        label: "Hadar Gachelet",
        name: "הדר-גחל",
        skinKey: "hadarGachelet",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/hadar-gachelet.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    // ── Laguna Shkiya (dark / teal-primary + warm-orange-secondary) ──
    {
        id: "lagunaShkiya",
        label: "Laguna Shkiya",
        name: "לגונה-שקיעה",
        skinKey: "lagunaShkiya",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/laguna-shkiya.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    // ── Menta Gachelet (dark / fresh mint-primary + warm-orange-secondary) ──
    {
        id: "mentaGachelet",
        label: "Menta Gachelet",
        name: "מנטה-גחל",
        skinKey: "mentaGachelet",
        group: "dark",
        previewImage: "/templates/previews/preview-covers/menta-gachelet.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    // ── Menta Shachar (light / fresh mint-primary + warm-orange-secondary) ──
    {
        id: "mentaShachar",
        label: "Menta Shachar",
        name: "מנטה-שחר",
        skinKey: "mentaShachar",
        group: "light",
        previewImage: "/templates/previews/preview-covers/menta-shachar.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },

    // ── Laguna Afarsek (light / teal-primary + peach-secondary) ──
    {
        id: "lagunaAfarsek",
        label: "Laguna Afarsek",
        name: "לגונה-אפרסק",
        skinKey: "lagunaAfarsek",
        group: "light",
        previewImage: "/templates/previews/preview-covers/laguna-afarsek.webp",
        supports: {
            backgroundImage: true,
            avatar: true,
            header: true,
            about: true,
            services: true,
            cta: true,
            socials: true,
            contact: true,
        },
        designDefaults: {
            backgroundMode: "photo",
            alignment: "left",
            socialStyle: "pills",
            fonts: { heading: "Heebo", body: "Assistant" },
            overlay: { enabled: true, color: "#000000", opacity: 0.35 },
        },
        seededFields: [
            "name",
            "headline",
            "company",
            "about",
            "faq",
            "cta.label",
            "cta.value",
            "contact.phone",
            "contact.email",
            "contact.website",
            "socials",
        ],
        sampleData: {
            name: "דניאל כהן",
            headline: "יועץ עסקי • אסטרטגיה וצמיחה",
            company: "כהן קונסלטינג",
            about: "עוזר לעסקים לבנות תהליך מכירה ברור, לשפר רווחיות ולהוציא רעיונות לפועל — בפשטות ובדיוק.",
            faq: {
                title: "שאלות ותשובות נפוצות",
                lead: "כמה תשובות קצרות שיעזרו להבין איך מתחילים ומה קורה בתהליך.",
                items: [
                    {
                        q: "איך מתחילים?",
                        a: "מתחילים בשיחה קצרה כדי להבין את הצורך, ואז קובעים פגישה ראשונה ומגדירים מטרות ברורות.",
                    },
                    {
                        q: "למי זה מתאים?",
                        a: "למי שרוצה סדר ובהירות בתהליך, לשפר תוצאות ולקבל החלטות בצורה מדויקת ומבוססת.",
                    },
                    {
                        q: "כמה זמן לוקח לראות תוצאות?",
                        a: "זה משתנה לפי מצב נקודת הפתיחה, אבל בדרך כלל כבר אחרי הצעדים הראשונים רואים שיפור במדדים ובתחוסת שליטה.",
                    },
                ],
            },
            cta: { label: "לפרטים נוספים", value: "https://example.com" },
            contact: {
                phone: "+972501234567",
                email: "daniel@example.com",
                website: "https://example.com",
            },
            socials: [
                { platform: "instagram", url: "https://instagram.com/example" },
                {
                    platform: "linkedin",
                    url: "https://linkedin.com/in/example",
                },
                { platform: "facebook", url: "https://facebook.com/example" },
            ],
        },
    },
];

// Keep existing exports, but ensure these work with TEMPLATES above.
export function normalizeTemplateId(raw) {
    const s = String(raw || "").trim();
    return s.length ? s : "roismanA11yLight";
}

export function getTemplateById(id) {
    const normalized = normalizeTemplateId(id);
    return TEMPLATES.find((t) => t.id === normalized) || TEMPLATES[0];
}
