export const PLANS = {
    free: {
        templates: [1], // только базовый шаблон
        galleryLimit: 4,
        leadForm: false,
        booking: false,
        video: false,
        reviews: false,
        publish: true,
        seo: false,
        analytics: false,
        slugChange: false,
        businessHours: false,
        services: false,
        contentParagraphs: 1,
    },

    monthly: {
        templates: "all",
        galleryLimit: 10,
        leadForm: true,
        booking: true,
        video: true,
        reviews: true,
        publish: true,
        seo: true,
        analytics: true,
        slugChange: true,
        businessHours: true,
        services: true,
        contentParagraphs: 3,
    },

    yearly: {
        templates: "all",
        galleryLimit: 10,
        leadForm: true,
        booking: true,
        video: true,
        reviews: true,
        publish: true,
        seo: true,
        analytics: true,
        slugChange: true,
        businessHours: true,
        services: true,
        contentParagraphs: 3,
    },

    org: {
        templates: "all",
        galleryLimit: 50,
        leadForm: true,
        booking: true,
        video: true,
        reviews: true,
        publish: true,
        seo: true,
        analytics: true,
        slugChange: true,
        businessHours: true,
        services: true,
        contentParagraphs: 3,
    },
};

export const PRICES_AGOROT = {
    monthly: 3990,
    yearly: 39990,
};
