/**
 * publicCardLabels.js — trusted, deterministic public-card visible labels.
 *
 * Scope: public card render (SSR + client). Values are constants only — no
 * owner-controlled text, no Date/Intl runtime formatting, no browser APIs — so
 * SSR renderToString and client hydration produce byte-identical output.
 *
 * Language resolution is defensive: only "ru" is honored; anything else
 * (including "he", undefined, null, or unknown) resolves to "he".
 */

export function resolvePublicCardLanguage(language) {
    return language === "ru" ? "ru" : "he";
}

export function resolvePublicCardDir(language) {
    return resolvePublicCardLanguage(language) === "ru" ? "ltr" : "rtl";
}

const LABELS = Object.freeze({
    he: Object.freeze({
        businessHoursTitle: "שעות פעילות",
        businessHoursShow: "הצג שעות פעילות",
        businessHoursHide: "הסתר שעות פעילות",
        closed: "סגור",
        weekdaysFull: Object.freeze({
            sun: "ראשון",
            mon: "שני",
            tue: "שלישי",
            wed: "רביעי",
            thu: "חמישי",
            fri: "שישי",
            sat: "שבת",
        }),
        galleryTitle: "גלריה",
        galleryAltWithName: (index, name) => `תמונה ${index} בגלריה של ${name}`,
        galleryAltNoName: (index) => `תמונה ${index} בגלריה`,
        reviewsTitle: "המלצות",
        reviewPrev: "המלצה הקודמת",
        reviewNext: "המלצה הבאה",
        reviewsAria: "המלצות",
        starRatingAria: (rating) => `דירוג ${rating} מתוך 5`,
        downloadQr: "הורד QR",
        bookingTitle: " תיאום תור",
        bookingWeekdayHeaders: Object.freeze([
            "א",
            "ב",
            "ג",
            "ד",
            "ה",
            "ו",
            "ש",
        ]),
        bookingMonths: Object.freeze([
            "ינואר",
            "פברואר",
            "מרץ",
            "אפריל",
            "מאי",
            "יוני",
            "יולי",
            "אוגוסט",
            "ספטמבר",
            "אוקטובר",
            "נובמבר",
            "דצמבר",
        ]),
        bookingPrevMonth: "חודש קודם",
        bookingNextMonth: "חודש הבא",
        videoTitle: "וידאו",
        servicesTitle: "שירותים",
        show: "הצג",
        hide: "הסתר",
        share: "שתף",
        saveToContacts: "שמור אותי באנשי קשר",
        contactPhone: "טלפון",
        contactWhatsapp: "וואטסאפ",
        contactFacebook: "פייסבוק",
        contactInstagram: "אינסטגרם",
        contactEmail: "אימייל",
        leadTitle: "צרו קשר",
        leadName: "שם מלא",
        leadEmail: "אימייל",
        leadPhone: "טלפון",
        leadMessage: "הודעה",
        leadSubmit: "שלח",
        leadSuccess: "תודה! פנייתך נשלחה בהצלחה",
        leadResend: "שלח הודעה נוספת",
        consentPrefixLead: "אני מסכים ל",
        consentPrefixBooking: "אני מסכים/ה ל",
        privacyPolicy: "מדיניות הפרטיות",
        consentConnectorLead: "וגם ל",
        consentConnectorBooking: "ול",
        termsOfUseSite: "תנאי השימוש באתר",
        termsOfUse: "תנאי השימוש",
        bookingIntro:
            "בחרו יום ושעה מתאימים, ובעל העסק ייצור איתכם קשר לאישור.",
        bookingSubmit: "שליחת בקשה",
        bookingSubmitting: "שולח…",
        website: "אתר",
        twitter: "טוויטר",
        tiktok: "טיקטוק",
        showMap: "הצג מפה",
        footerSharePrefix: "שתפו את ",
        footerShareFallback: "שתפו",
        shareFacebook: "שתף בפייסבוק",
        shareEmail: "שתף במייל",
        shareWhatsapp: "שתף בוואטסאפ",
        footerBuiltPrefix: "נבנה ב־",
        footerBuiltSuffix: " - הדרך החכמה לכרטיס ביקור דיגיטלי מקצועי",
        footerInstallAndroid: "התקינו את Cardigo לאנדרואיד",
        shareUnavailableUntilPublished: "אפשר לשתף רק אחרי פרסום הכרטיס",
    }),
    ru: Object.freeze({
        businessHoursTitle: "Часы работы",
        businessHoursShow: "Показать часы работы",
        businessHoursHide: "Скрыть часы работы",
        closed: "Закрыто",
        weekdaysFull: Object.freeze({
            sun: "Воскресенье",
            mon: "Понедельник",
            tue: "Вторник",
            wed: "Среда",
            thu: "Четверг",
            fri: "Пятница",
            sat: "Суббота",
        }),
        galleryTitle: "Галерея",
        galleryAltWithName: (index, name) =>
            `Изображение ${index} в галерее ${name}`,
        galleryAltNoName: (index) => `Изображение ${index} в галерее`,
        reviewsTitle: "Отзывы",
        reviewPrev: "Предыдущий отзыв",
        reviewNext: "Следующий отзыв",
        reviewsAria: "Отзывы",
        starRatingAria: (rating) => `Рейтинг ${rating} из 5`,
        downloadQr: "Скачать QR",
        bookingTitle: "Запись на встречу",
        bookingWeekdayHeaders: Object.freeze([
            "Вс",
            "Пн",
            "Вт",
            "Ср",
            "Чт",
            "Пт",
            "Сб",
        ]),
        bookingMonths: Object.freeze([
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь",
        ]),
        bookingPrevMonth: "Предыдущий месяц",
        bookingNextMonth: "Следующий месяц",
        videoTitle: "Видео",
        servicesTitle: "Услуги",
        show: "Показать",
        hide: "Скрыть",
        share: "Поделиться",
        saveToContacts: "Сохранить в контакты",
        contactPhone: "Телефон",
        contactWhatsapp: "WhatsApp",
        contactFacebook: "Facebook",
        contactInstagram: "Instagram",
        contactEmail: "Email",
        leadTitle: "Связаться",
        leadName: "Полное имя",
        leadEmail: "Email",
        leadPhone: "Телефон",
        leadMessage: "Сообщение",
        leadSubmit: "Отправить",
        leadSuccess: "Спасибо! Ваше сообщение успешно отправлено",
        leadResend: "Отправить ещё одно сообщение",
        consentPrefixLead: "Я соглашаюсь с ",
        consentPrefixBooking: "Я соглашаюсь с ",
        privacyPolicy: "Политикой конфиденциальности",
        consentConnectorLead: "и ",
        consentConnectorBooking: "и ",
        termsOfUseSite: "Условиями использования сайта",
        termsOfUse: "Условиями использования сайта",
        bookingIntro:
            "Выберите удобный день и время, и владелец бизнеса свяжется с вами для подтверждения.",
        bookingSubmit: "Отправить запрос",
        bookingSubmitting: "Отправка…",
        website: "Сайт",
        twitter: "Twitter",
        tiktok: "TikTok",
        showMap: "Показать карту",
        footerSharePrefix: "Поделиться ",
        footerShareFallback: "Поделиться",
        shareFacebook: "Поделиться в Facebook",
        shareEmail: "Поделиться по Email",
        shareWhatsapp: "Поделиться в WhatsApp",
        footerBuiltPrefix: "Создано в ",
        footerBuiltSuffix:
            " — умный способ создать профессиональную цифровую визитку",
        footerInstallAndroid: "Установить Cardigo для Android",
        shareUnavailableUntilPublished:
            "Поделиться можно только после публикации карточки",
    }),
});

export function getPublicCardLabels(language) {
    return LABELS[resolvePublicCardLanguage(language)];
}
